/*
Immediate Generator test bench
Author: Luke Pearcy
Date: 2/1/2024
*/


`timescale 1ns / 1ps

module tb_ImmediateGenerator

  //input/output
  reg [15:0] input_imm, // 16-bit input of the instruction for the immediate to be parsed
  wire [15:0] output_imm // 16-bit output representing the immediate value generated by the Immediate Generator.

  //unit under test
  ImmediateGenerator UUT(
    .input_imm(input_imm),
    .output_imm(output_imm)
  );

  initial begin
    // Test 1: test LUI for setting UI register
    input_imm = 0000000001000 001; //sets UI to 64
    #10
    if(output_imm!=0000 0000 0000 0000) 
      $display("Immediate Generator Test 1 failed:  LUI instruction output was not 0");

    // Test 2: generating immediate for 2RI instruction using UI register
    input_imm =  000 000 010 0000 010; //2RI instruction: addi x0, x0, 2
    #10
    if(output_imm!=0000 0000 0100 0010) //immediate should be 64+2=66
      $display("Immediate Generator Test 2 failed:  immediate for 2RI instruction was not UI with provided immediate appended");

    // Test 3: test immediate for UJ type
    input_imm = 000 0111110100 011; //UJ instruction: jal x0 500
    #10 
    if(output_imm!=0000 0001 1111 0100) // immediate should be 500
      $display("Immediate Generator Test 3 failed:  UJ immediate was not given value in instruction");

    // Test 4: test immediate for RI type
    input_imm =000 110010 0000 100; //RI instruction: inc x0, 50
    #10
    if(output_imm!=0000 0000 0011 0010) //immediate should be 50
      $display("Immediate Generator Test 4 failed:  ");

    $stop;
  end

endmodule
